# Cloze Fine-tuning Project Configuration
# This file contains the default configuration parameters for the project

# Project metadata
project_name: "cloze-finetuning"
version: "1.0.0"
author: "Maria Mouratidi"

# Paths
data_dir: "datasets"
output_dir: "outputs"
models_dir: "models"
logs_dir: "logs"
plots_dir: "plots"

# Model configuration
base_model: "gpt2"
use_special_tokens: true
max_length: 512

# Training configuration
num_epochs: 6
batch_size: 1
learning_rate: 0.00005  # 5e-5
warmup_steps: 200
weight_decay: 0.01
random_seed: 42

# Data configuration
datasets_to_use:
  - "cloze"
  - "peelle"
  - "provo"
max_samples_per_dataset: 2000
train_test_split: 0.9

# Evaluation configuration
evaluation_datasets:
  - "cloze"
  - "gpt2"
  - "wikipedia"
create_plots: true
save_results: true

# Computing configuration
device: "auto"  # auto, cpu, or cuda
num_workers: 4